In [1]:
%load_ext autoreload
%autoreload 2
%reload_ext autoreload

In [2]:
import os
import pickle
import numpy as np
import pandas as pd
import plotly.express as px
import matplotlib.pyplot as plt
from pymoo.indicators.hv import Hypervolume

from util import natural_key, load_yaml

In [3]:
def load_pareto_history(filepath="pareto_history.pkl"):
    """
    Carga el archivo pickle que contiene fronts_history.
    Devuelve un dict: {generacion: {nivel_frente: [registros...]}}
    """
    with open(filepath, "rb") as f:
        history = pickle.load(f)
    return history

In [4]:
def pareto_history_to_df(filepath="pareto_history.pkl", generation=None):
    """
    Convierte la historia de Pareto guardada en filepath en un DataFrame
    para la generación 'generation', con columnas:
        generation, front_level, accuracy, params, inference_time
    """
    history = load_pareto_history(filepath)
        
    if generation is None:
        generation = max(history.keys())
        
    gen_dict = history[generation]
    records = []
    for level, recs in gen_dict.items():
        # saltamos la métrica hypervolume
        if level == "hypervolume":
            continue
        for rec in recs:
            records.append({
                "id":             rec["id"],
                "generation":      generation,
                "front_level":     level,
                "accuracy":        rec["accuracy"],
                "params":          rec["params"],
                "inference_time":  rec["inference_time"]
            })
    return pd.DataFrame(records)

In [5]:
def archive_to_df(experiment_path: str, archive_subdir: str = "archive") -> pd.DataFrame:
    """Load training metrics from the archive directory into a DataFrame.

    Each folder inside ``archive_subdir`` should contain a ``training_params.txt``
    file with keys such as ``fitness_metric``, ``cuda_inference_time`` and
    ``total_params``. The value for ``fitness_metric`` is taken from the metric
    name specified in that file.

    Parameters
    ----------
    experiment_path : str
        Path to the root experiment directory.
    archive_subdir : str, optional
        Name of the subdirectory that stores archived results. Defaults to
        ``"archive"``.

    Returns
    -------
    pandas.DataFrame
        DataFrame with columns ``id``, ``fitness_metric``, ``cuda_inference_time``
        and ``total_params`` for all archived runs.
    """

    archive_dir = os.path.join(experiment_path, archive_subdir)
    if not os.path.isdir(archive_dir):
        raise FileNotFoundError(f"Archive folder not found at {archive_dir}")

    records = []
    for folder in sorted(os.listdir(archive_dir), key=natural_key):
        params_file = os.path.join(archive_dir, folder, "training_params.txt")
        if not os.path.isfile(params_file):
            continue

        params = load_yaml(params_file)
        metric_key = params.get("fitness_metric")
        if metric_key is None:
            continue

        fitness_value = params.get(metric_key)
        cuda_time = params.get("cuda_inference_time")
        tot_params = params.get("total_params")

        records.append(
            {
                "id": folder,
                "fitness_metric": fitness_value,
                "cuda_inference_time": cuda_time,
                "total_params": tot_params,
            }
        )

    return pd.DataFrame(records)

In [6]:
path_archive = "experiment_cifar10_nsgaX/exp2_repeat_1"
df_archive = archive_to_df(path_archive)
df_archive.shape

(52, 4)

In [7]:
df_archive

       id  fitness_metric  cuda_inference_time  total_params
0    0_18            52.6           339.961052         24554
1    1_16            54.4           432.848930        368554
2    1_18            51.7           344.276428         22570
3     2_1            48.1          2942.276001          7210
4     2_2            56.9          6416.845322        139530
5     2_8            56.6          2736.616135         73706
6    2_12            57.2          1982.021332        380906
7    2_16            47.3          4275.512695          6442
8    2_19            54.6          1820.325851         85994
9    3_16            50.4           525.331497         21098
10    4_2            53.1          5134.677887         25674
11   4_16            52.7          4909.873009         29642
12    5_0            27.3          5123.066902          1482
13    5_8            54.5          5820.083618         25674
14   5_15            47.3           315.594673         21098
15    6_1            56.7          3489.661217        103658
16    6_6            55.3          6964.707375         22570
17    6_8            64.7           393.009186        786890
18   6_10            60.2          6556.487083         40938
19   6_19            57.8          3037.786484        380906
20    7_1            56.5         11174.058914         22570
21    7_2            49.9         10331.535339         12170
22    7_3            29.9          9224.247932          1482
23    7_5            60.3          9036.231041         40938
24    7_8            64.9          5552.816391        488138
25   7_14            57.1           606.131554        198442
26   7_15            59.9          5136.895180        161034
27    9_4            63.2          2857.232094        488138
28    9_6            56.4          7946.133614         36458
29   9_11            51.6          8657.836914         15402
30   9_14            52.6          4238.581657         22570
31  10_19            27.8          7172.250748          1482
32  11_17            35.7          7386.827469          3786
33  11_18            42.1          7814.741135          6090
34   12_1            45.4         14686.012268          6090
35   12_2            59.6          4492.354393        456394
36  12_16            51.8           328.612328        349258
37  12_19            36.1           211.620331          4490
38   14_2            66.5          8716.058731        488138
39   14_7            65.5          3469.800949        786890
40  14_17            64.4           394.272804        692586
41  15_14            47.0           203.657150         48650
42  15_19            14.9          6697.034836           130
43   16_8            61.1         11979.889870        161034
44  16_12            62.3           394.511223        488138
45  16_13            24.2          8002.018929           490
46  16_16            14.7           236.606598           130
47   18_2            57.6          4848.718643        186538
48  18_11            41.8          9797.024727          5322
49  18_12            61.5          6775.045395        393834
50   19_5            37.4          8407.592773          5322
51   19_7            16.0         10544.204712           130

In [8]:
pkl_path = os.path.join(path_archive, "pareto_history.pkl")
df_history = pareto_history_to_df(pkl_path)
df_history = df_history[df_history["front_level"] == 1]

In [9]:
# check if there are some ids that has the same values in accuracy, params and inference_time, in df_history, if so, remove the ones that are not in df_archive
duplicated_rows = df_history[df_history.duplicated(subset=['accuracy', 'params', 'inference_time'], keep=False)]
if not duplicated_rows.empty:
    print("Duplicated rows found")
    archive_ids = set(df_archive['id'])
    rows_to_remove = duplicated_rows[~duplicated_rows['id'].isin(archive_ids)]
    if not rows_to_remove.empty:
        print(f"Removing {len(rows_to_remove)} rows")
        df_history = df_history.drop(rows_to_remove.index)

In [10]:
df_history

       id  generation  front_level  accuracy    params  inference_time
0    0_18          19            1      52.6   24554.0      339.961052
1   10_19          19            1      27.8    1482.0     7172.250748
2   11_17          19            1      35.7    3786.0     7386.827469
3   11_18          19            1      42.1    6090.0     7814.741135
4    12_1          19            1      45.4    6090.0    14686.012268
5   12_16          19            1      51.8  349258.0      328.612328
6   12_19          19            1      36.1    4490.0      211.620331
7    12_2          19            1      59.6  456394.0     4492.354393
8   14_17          19            1      64.4  692586.0      394.272804
9    14_2          19            1      66.5  488138.0     8716.058731
10   14_7          19            1      65.5  786890.0     3469.800949
11  15_14          19            1      47.0   48650.0      203.657150
12  15_19          19            1      14.9     130.0     6697.034836
13  16_12          19            1      62.3  488138.0      394.511223
14  16_13          19            1      24.2     490.0     8002.018929
15  16_16          19            1      14.7     130.0      236.606598
16   16_8          19            1      61.1  161034.0    11979.889870
17  18_11          19            1      41.8    5322.0     9797.024727
18  18_12          19            1      61.5  393834.0     6775.045395
19   18_2          19            1      57.6  186538.0     4848.718643
20   19_5          19            1      37.4    5322.0     8407.592773
21   19_7          19            1      16.0     130.0    10544.204712
22   1_16          19            1      54.4  368554.0      432.848930
23   1_18          19            1      51.7   22570.0      344.276428
24    2_1          19            1      48.1    7210.0     2942.276001
25   2_12          19            1      57.2  380906.0     1982.021332
26   2_16          19            1      47.3    6442.0     4275.512695
27   2_19          19            1      54.6   85994.0     1820.325851
28    2_2          19            1      56.9  139530.0     6416.845322
29    2_8          19            1      56.6   73706.0     2736.616135
30   3_16          19            1      50.4   21098.0      525.331497
31   4_16          19            1      52.7   29642.0     4909.873009
32    4_2          19            1      53.1   25674.0     5134.677887
33    5_0          19            1      27.3    1482.0     5123.066902
34   5_15          19            1      47.3   21098.0      315.594673
35    5_8          19            1      54.5   25674.0     5820.083618
36    6_1          19            1      56.7  103658.0     3489.661217
37   6_10          19            1      60.2   40938.0     6556.487083
38   6_19          19            1      57.8  380906.0     3037.786484
39    6_6          19            1      55.3   22570.0     6964.707375
40    6_8          19            1      64.7  786890.0      393.009186
41    7_1          19            1      56.5   22570.0    11174.058914
42   7_14          19            1      57.1  198442.0      606.131554
43   7_15          19            1      59.9  161034.0     5136.895180
44    7_2          19            1      49.9   12170.0    10331.535339
45    7_3          19            1      29.9    1482.0     9224.247932
46    7_5          19            1      60.3   40938.0     9036.231041
47    7_8          19            1      64.9  488138.0     5552.816391
48   9_11          19            1      51.6   15402.0     8657.836914
49   9_14          19            1      52.6   22570.0     4238.581657
50    9_4          19            1      63.2  488138.0     2857.232094
51    9_6          19            1      56.4   36458.0     7946.133614

In [11]:
# check if there are any different ids in the archive and history
archive_ids = set(df_archive["id"])
history_ids = set(df_history["id"])
print(f"Archive IDs: {len(archive_ids)}")
print(f"History IDs: {len(history_ids)}")
print(f"Different IDs: {len(archive_ids - history_ids)}")
# check the values of the ids that are in the archive but not in the history
diff_ids = archive_ids - history_ids
print("Different IDs:", diff_ids)

Archive IDs: 52
History IDs: 52
Different IDs: 0
Different IDs: set()